/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicSignupRouteImport } from './routes/_public/signup'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthenticatedSpaceRouteImport } from './routes/_authenticated/space'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSpaceSpaceSlugRouteImport } from './routes/_authenticated/space.$spaceSlug'
import { Route as AuthenticatedSettingsConnectionsRouteImport } from './routes/_authenticated/settings/connections'
import { Route as AuthenticatedSettingsRepositoriesIndexRouteImport } from './routes/_authenticated/settings/repositories/index'
import { Route as AuthenticatedSettingsRepositoriesConnectRouteImport } from './routes/_authenticated/settings/repositories/connect'
import { Route as AuthenticatedSettingsRepositoriesRepositoryIdEditRouteImport } from './routes/_authenticated/settings/repositories/$repositoryId.edit'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicSignupRoute = PublicSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedSpaceRoute = AuthenticatedSpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSpaceSpaceSlugRoute =
  AuthenticatedSpaceSpaceSlugRouteImport.update({
    id: '/$spaceSlug',
    path: '/$spaceSlug',
    getParentRoute: () => AuthenticatedSpaceRoute,
  } as any)
const AuthenticatedSettingsConnectionsRoute =
  AuthenticatedSettingsConnectionsRouteImport.update({
    id: '/connections',
    path: '/connections',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsRepositoriesIndexRoute =
  AuthenticatedSettingsRepositoriesIndexRouteImport.update({
    id: '/repositories/',
    path: '/repositories/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsRepositoriesConnectRoute =
  AuthenticatedSettingsRepositoriesConnectRouteImport.update({
    id: '/repositories/connect',
    path: '/repositories/connect',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsRepositoriesRepositoryIdEditRoute =
  AuthenticatedSettingsRepositoriesRepositoryIdEditRouteImport.update({
    id: '/repositories/$repositoryId/edit',
    path: '/repositories/$repositoryId/edit',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/space': typeof AuthenticatedSpaceRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/space/$spaceSlug': typeof AuthenticatedSpaceSpaceSlugRoute
  '/settings/repositories/connect': typeof AuthenticatedSettingsRepositoriesConnectRoute
  '/settings/repositories/': typeof AuthenticatedSettingsRepositoriesIndexRoute
  '/settings/repositories/$repositoryId/edit': typeof AuthenticatedSettingsRepositoriesRepositoryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/space': typeof AuthenticatedSpaceRouteWithChildren
  '/login': typeof PublicLoginRoute
  '/signup': typeof PublicSignupRoute
  '/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/space/$spaceSlug': typeof AuthenticatedSpaceSpaceSlugRoute
  '/settings/repositories/connect': typeof AuthenticatedSettingsRepositoriesConnectRoute
  '/settings/repositories': typeof AuthenticatedSettingsRepositoriesIndexRoute
  '/settings/repositories/$repositoryId/edit': typeof AuthenticatedSettingsRepositoriesRepositoryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/space': typeof AuthenticatedSpaceRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_public/signup': typeof PublicSignupRoute
  '/_authenticated/settings/connections': typeof AuthenticatedSettingsConnectionsRoute
  '/_authenticated/space/$spaceSlug': typeof AuthenticatedSpaceSpaceSlugRoute
  '/_authenticated/settings/repositories/connect': typeof AuthenticatedSettingsRepositoriesConnectRoute
  '/_authenticated/settings/repositories/': typeof AuthenticatedSettingsRepositoriesIndexRoute
  '/_authenticated/settings/repositories/$repositoryId/edit': typeof AuthenticatedSettingsRepositoriesRepositoryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/space'
    | '/login'
    | '/signup'
    | '/settings/connections'
    | '/space/$spaceSlug'
    | '/settings/repositories/connect'
    | '/settings/repositories/'
    | '/settings/repositories/$repositoryId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/space'
    | '/login'
    | '/signup'
    | '/settings/connections'
    | '/space/$spaceSlug'
    | '/settings/repositories/connect'
    | '/settings/repositories'
    | '/settings/repositories/$repositoryId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/settings'
    | '/_authenticated/space'
    | '/_public/login'
    | '/_public/signup'
    | '/_authenticated/settings/connections'
    | '/_authenticated/space/$spaceSlug'
    | '/_authenticated/settings/repositories/connect'
    | '/_authenticated/settings/repositories/'
    | '/_authenticated/settings/repositories/$repositoryId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/signup': {
      id: '/_public/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof PublicSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/space': {
      id: '/_authenticated/space'
      path: '/space'
      fullPath: '/space'
      preLoaderRoute: typeof AuthenticatedSpaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/space/$spaceSlug': {
      id: '/_authenticated/space/$spaceSlug'
      path: '/$spaceSlug'
      fullPath: '/space/$spaceSlug'
      preLoaderRoute: typeof AuthenticatedSpaceSpaceSlugRouteImport
      parentRoute: typeof AuthenticatedSpaceRoute
    }
    '/_authenticated/settings/connections': {
      id: '/_authenticated/settings/connections'
      path: '/connections'
      fullPath: '/settings/connections'
      preLoaderRoute: typeof AuthenticatedSettingsConnectionsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/repositories/': {
      id: '/_authenticated/settings/repositories/'
      path: '/repositories'
      fullPath: '/settings/repositories/'
      preLoaderRoute: typeof AuthenticatedSettingsRepositoriesIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/repositories/connect': {
      id: '/_authenticated/settings/repositories/connect'
      path: '/repositories/connect'
      fullPath: '/settings/repositories/connect'
      preLoaderRoute: typeof AuthenticatedSettingsRepositoriesConnectRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/repositories/$repositoryId/edit': {
      id: '/_authenticated/settings/repositories/$repositoryId/edit'
      path: '/repositories/$repositoryId/edit'
      fullPath: '/settings/repositories/$repositoryId/edit'
      preLoaderRoute: typeof AuthenticatedSettingsRepositoriesRepositoryIdEditRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsConnectionsRoute: typeof AuthenticatedSettingsConnectionsRoute
  AuthenticatedSettingsRepositoriesConnectRoute: typeof AuthenticatedSettingsRepositoriesConnectRoute
  AuthenticatedSettingsRepositoriesIndexRoute: typeof AuthenticatedSettingsRepositoriesIndexRoute
  AuthenticatedSettingsRepositoriesRepositoryIdEditRoute: typeof AuthenticatedSettingsRepositoriesRepositoryIdEditRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsConnectionsRoute: AuthenticatedSettingsConnectionsRoute,
  AuthenticatedSettingsRepositoriesConnectRoute:
    AuthenticatedSettingsRepositoriesConnectRoute,
  AuthenticatedSettingsRepositoriesIndexRoute:
    AuthenticatedSettingsRepositoriesIndexRoute,
  AuthenticatedSettingsRepositoriesRepositoryIdEditRoute:
    AuthenticatedSettingsRepositoriesRepositoryIdEditRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedSpaceRouteChildren {
  AuthenticatedSpaceSpaceSlugRoute: typeof AuthenticatedSpaceSpaceSlugRoute
}

const AuthenticatedSpaceRouteChildren: AuthenticatedSpaceRouteChildren = {
  AuthenticatedSpaceSpaceSlugRoute: AuthenticatedSpaceSpaceSlugRoute,
}

const AuthenticatedSpaceRouteWithChildren =
  AuthenticatedSpaceRoute._addFileChildren(AuthenticatedSpaceRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedSpaceRoute: typeof AuthenticatedSpaceRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedSpaceRoute: AuthenticatedSpaceRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
  PublicSignupRoute: typeof PublicSignupRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
  PublicSignupRoute: PublicSignupRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
